### PR TITLE
catchup.py temp workaround for catch-up

### PR DESCRIPTION
**Pull request by davesayers2014**
M3u8 doesn't work

### CODE REVIEW

**Comment by kiddac** [comment]
@davesayers2014 That would still break

image

**Comment by kiddac** [comment]
this is probably better

image

**Comment by kiddac** [comment]
this has been updated now with the latter code above.

**Comment by davesayers2014** [comment]
That works. Thanks

My PR only fixed catch-up on .ts. You're update works for both .ts and m3u8

**Pull request closed without merging**
