### PR TITLE
[setupbouquet.py] "setList" before "updateList"

### PR DESCRIPTION
**Pull request by Huevos**

### CODE REVIEW

**Comment by kiddac** [comment]
The whole point of using updatelist is not to use setlist. So recommending using setlist before updatelist in this function is not the solution to this problem. 

	def updateList(self, list):
		"""Changes the list without changing the selection or emitting changed Events"""

But there is an error in my code, as I don't actually set the list anywhere on load. 

image

**Comment by kiddac** [comment]
The problem lies is in your list.py 

	def getIndex(self):
		return self.master.index if self.master is not None else None

this should actually return 0

@Huevos

**Comment by Huevos** [comment]
The problem is how your plugin is using this. No other code has problems with this because it is being used as intended.

https://github.com/OpenPLi/enigma2/blob/develop/lib/python/Screens/Satconfig.py#L317-L318

**Comment by Huevos** [comment]
Only reason this plugin ever worked in Py2 is because asserts are only triggered during debug mode.

**Comment by kiddac** [comment]
My JediMakerXtream plugin has now been updated and should now be fully functional with openvix new code.

**Comment by Huevos** [comment]
Cool. 

If possible, xstremity needs the same fix.

**Pull request closed without merging**
